manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: samuelliden
      url-base: https://github.com/samuelliden
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-paw3395-driver
      remote: badjeff
      revision: main
    - name: zmk-paw3395-mouse
      remote: samuelliden
      revision: main
  self:
    path: config
