name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Fetch Build Keyboards
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install yaml2json
        run: python3 -m pip install remarshal
      - id: set-matrix
        name: Fetch Build Matrix
        run: |
          matrix=$(yaml2json config/build.yaml | jq -c .)
          yaml2json config/build.yaml
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    needs: matrix
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - name: Prepare variables
        shell: sh -x {0}
        run: |
          echo "zephyr_version=${ZEPHYR_VERSION}" >> $GITHUB_ENV
          echo "extra_cmake_args=${shield:+-DSHIELD=\"$shield\"}${snippet:+ -DSNIPPET=\"$snippet\"}${artifact_name:+ -DCONFIG_ZMK_KEYBOARD_NAME=\"$artifact_name\"} -DBOARD_ROOT=\"$GITHUB_WORKSPACE/project/config\"" >> $GITHUB_ENV
          echo "display_name=${shield:+$shield - }${board}${artifact_name:+ - $artifact_name}" >> $GITHUB_ENV
          echo "artifact_name=${artifact_name:-${shield:+$shield-}${board}-zmk}" >> $GITHUB_ENV

      - name: Create workspace
        run: mkdir -p workspace

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: workspace/project

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        env:
          cache_name: cache-zephyr-${{ env.zephyr_version }}-modules
        with:
          path: |
            workspace/modules/
            workspace/tools/
            workspace/zephyr/
            workspace/bootloader/
            workspace/zmk/
          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('workspace/project/config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache_name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        working-directory: workspace
        run: west init -l project/config

      - name: West Update
        working-directory: workspace
        run: west update

      - name: West Zephyr export
        working-directory: workspace
        run: west zephyr-export

      - name: West Build (${{ env.display_name }})
        working-directory: workspace
        shell: sh -x {0}
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DZMK_CONFIG="$GITHUB_WORKSPACE/workspace/project/config" ${{ env.extra_cmake_args }}

      - name: ${{ env.display_name }} Kconfig file
        working-directory: workspace
        run: grep -v -e "^#" -e "^$" build/zephyr/.config | sort

      - name: Rename artifacts
        working-directory: workspace
        shell: sh -x {0}
        run: |
          mkdir -p build/artifacts
          if [ -f build/zephyr/zmk.uf2 ]
          then
            cp build/zephyr/zmk.uf2 "build/artifacts/${{ env.artifact_name }}.uf2"
          elif [ -f build/zephyr/zmk.hex ]
          then
            cp build/zephyr/zmk.hex "build/artifacts/${{ env.artifact_name }}.hex"
          fi

      - name: Archive (${{ env.display_name }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: workspace/build/artifacts
