name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-build-arm:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            .west
            zephyr
            modules
            tools
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West init
        run: west init -l config
      - name: West update
        run: west update
      - name: West config ZMK
        run: west config build.cmake-args -- -DZMK_CONFIG="$(pwd)/config" -DSHIELD="${{ matrix.shield }}" -DZMK_EXTRA_MODULES="$(pwd)"
      - name: West build
        run: west build -s zmk/app -d build -b seeeduino_xiao_ble -- -DZMK_CONFIG="$(pwd)/config" -DSHIELD=paw3395 -DZMK_EXTRA_MODULES="$(pwd)"
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: PAW3395 Mouse
          path: build/zephyr/zmk.uf2